// ignore_for_file: file_names

import 'package:e3tmed/logic/interfaces/IAgentOperations.dart';
import 'package:e3tmed/logic/interfaces/INotificationsManager.dart';
import 'package:e3tmed/models/agent_requests_model.dart';
import 'package:e3tmed/models/order.dart';

enum AllStrings {
  phoneNumberTitle,
  passwordTitle,
  receivedCodeTitle,
  newPasswordTitle,
  confirmPasswordTitle,
  currentPasswordTitle,
  enterTitle,
  verifyTitle,
  submitTitle,
  confirmTitle,
  forgotPasswordTitle,
  changePasswordTitle,
  didYouForgetYourPasswordTitle,
  enterYourPhoneNumberToReceiveTheValidationCodeTitle,
  youWillReceiveACodeToVerifyYourPhoneNumberPleaseWriteItDownWhenYouReceiveItTitle,
  youWillReceiveACodeToResetYourPasswordPleaseWriteItDownWhenYouReceiveItTitle,
  codeTitle,
  confirmationCodeTitle,
  loginTitle,
  dontHaveAccountTitle,
  registerNowTitle,
  createNewAccountTitle,
  step1Title,
  step2Title,
  nextTitle,
  alreadyUserTitle,
  loginNowTitle,
  firstNameTitle,
  lastNameTitle,
  emailTitle,
  countryTitle,
  cityTitle,
  regionTitle,
  addressTitle,
  registerTitle,
  homeTitle,
  goodMorningTitle,
  pleaseChooseTheNeededServiceTitle,
  profileTitle,
  offersTitle,
  helpTitle,
  myOrdersTitle,
  aboutTitle,
  helloTitle,
  instructionsTitle,
  nameTitle,
  messageTitle,
  sendTitle,
  aboutMessageTile,
  continueTitle,
  startYourOrdersAndContactWithClientsTitle,
  requestsTitle,
  notificationTitle,
  youDontHaveNotificationYetTitle,
  logoutTitle,
  areYouSureYouWantToLogoutTitle,
  yesTitle,
  noTitle,
  allTitle,
  newTitle,
  repairTitle,
  pendingTitle,
  confirmedTitle,
  completedTitle,
  priceDetailsTitle,
  totalTitle,
  productPriceTitle,
  agentFeesTitle,
  acceptTitle,
  viewDetailsTitle,
  itemDetailsTitle,
  contactViaWhatsAppTitle,
  editDetailsTitle,
  dimensionsTitle,
  thicknessTitle,
  colorTitle,
  motorTitle,
  addSparePartsTitle,
  addExtrasTitle,
  addNoteTitle,
  noteTitle,
  saveAndContinueTitle,
  orderConfirmedTitle,
  orderInstalledTitle,
  completeTitle,
  orderDetailsTitle,
  vatTitle,
  cartTitle,
  settingsTitle,
  changeNameTitle,
  addressesTitle,
  changePhoneNumberTitle,
  changeEmailTitle,
  yourListIsEmptyTitle,
  deliverToTitle,
  subtotalTitle,
  askForAgentTitle,
  addDimensionsTitle,
  continueCheckoutTitle,
  addToCartTitle,
  priceSummaryTitle,
  productCostTitle,
  paymentMethodTitle,
  changePaymentTitle,
  termAndConditionsTitle,
  iHaveReadAndAcceptedTermAdnConditionsTitle,
  confirmOrderTitle,
  proceedToBuyTitle,
  itemsTitle,
  deleteTitle,
  cancelTitle,
  newPhoneNumberTitle,
  changeAddressTitle,
  addCardTitle,
  cardNumberTitle,
  expiryDateTitle,
  cvvTitle,
  cardHolderFirstNameTitle,
  cardHolderLastNameTitle,
  changeTitle,
  enterThePhoneNumberTitle,
  isRequiredTitle,
  enterCorrectTitle,
  maintenanceTitle,
  agentVisitTitle,
  sparePartsTitle,
  extrasAndServicesTitle,
  orderSummaryTitle,
  changeLanguageTitle,
  priceMayChangeAccordingToAgentsVisitAndFeesWillBeDeductedFromTotalPaymentWhenTheRequestIsCompletedTitle,
  ifYouDontKnowTheDoorDimensionsYouCanAskForAnAgentTitle,
  newEmailTitle,
  quantityTitle,
  addPhotoTitle,
  specificationTitle,
  photosTitle,
  widthTitle,
  heightTitle,
  cannotStartWithZero,
  emailAndPhoneAreAlreadyExistTitle,
  emailIsAlreadyExistTitle,
  phoneIsAlreadyExistTitle,
  emailOrPassowrdAreIncorrectTitle,
  phoneOrPasswordAreIncorrectTitle,
  youWillBeReceivingCodeInTitle,
  resendCodeAgainTitle,
  secondsTitle,
  cancelOrderTitle,
  areYouSureYouWantToCancelOrderTitle,
  orderCanceledSuccessfullyTitle,
  failedToCancelOrderTitle,
  passwordAndConfirmPasswordDoesntMatchTitle,
  registerSuccessfulPleaseLoginTitle,
  changedSuccessfullyTitle,
  orderRemovedFromCartTitle,
  failedToRemoveOrderFromCartTitle,
  thanksForContactingUsTitle,
  failedToSendMessageTitle,
  orderAddedToCartTitle,
  failedToAddOrderToCartTitle,
  thanksForOrderingTitle,
  nameChangedSuccessfullyTitle,
  errorWhileChangingNameTitle,
  pleaseSelectAnAddressToContinueTitle,
  emailChangedSuccessfullyTitle,
  errorWhileChangingEmailTitle,
  passwordChangedSuccessfullyTitle,
  errorWhileChangingPasswordTitle,
  phoneNumberChangedSuccessfullyTitle,
  errorWhileChangingPhoneNumberTitle,
  orderCanceledTitle,
  newVersionTitle,
  aNewVersionHasBeenReleasedPleaseUpdateTitle,
  updateTitle,
  paymentMethodCashTitle,
  paymentMethodCardTitle,
  editTitle,
  deleteAddressTitle,
  areYouSureYouWantToDeleteThisAddressTitle,
  paidAmount,
  totalDue
}

abstract class IStrings {
  String getStrings(AllStrings string);

  String getNotificationMessage(NotificationType type, Order order,
      [OrderStatus? oldOrderStatus]);

  String getNotificationTypeString(NotificationType type);

  String getOrderFilterString(AgentOrderFilters filter);

  String getOrderStatusString(OrderStatus status);

  String getUserOrderStatusInformationString(OrderStatus status);

  String getOrderAgentStatusInformationString(OrderStatus status);
}
